"""option and log_entry

Revision ID: 303092990308
Revises: 32086ae6e45a
Create Date: 2023-07-10 09:32:57.417766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303092990308'
down_revision = '32086ae6e45a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.BigInteger(), nullable=True),
    sa.Column('stack', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date_created')
    )
    op.create_table('option',
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('wizlock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('date_created')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    op.drop_table('log_entry')
    # ### end Alembic commands ###
