"""tweak options

Revision ID: cc539ecc4805
Revises: 303092990308
Create Date: 2023-07-10 14:25:36.032495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc539ecc4805'
down_revision = '303092990308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('option', sa.Column('db_version', sa.String(), nullable=True))
    op.add_column('option', sa.Column('code_version', sa.String(), nullable=True))
    #op.drop_column('option', 'version')
    # ### end Alembic commands ###
    op.alter_column('option', 'version', new_column_name='db_version')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('option', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('option', 'code_version')
    #op.drop_column('option', 'db_version')
    # ### end Alembic commands ###
    op.alter_column('option', 'db_version', new_column_name='version')
